### ISSUE TITLE
Cluster details in Metrics

### ISSUE THREAD

**Issue by rjshrjndrn** [criteo/cassandra_exporter#88]
Hi,
As per PR #79, it's possible to scrape the cluster information from the exporter. But with the default configuration, we're not getting that. Is there any flag we've to enable  or is there any documentation for that? Please suggest.

**Comment by rjshrjndrn** [comment]
Okay I figured out that we're blacklisting the `org.apache.cassandra.db:*` bean and because of that we're not getting the `StorageService` metrics. 
@erebe Is there any way to whitelist only this metrics ?

**Comment by rjshrjndrn** [comment]
Hi @erebe Any comments on this ?

**Comment by erebe** [comment]
You change the config in order to blacklist just the path you don't want instead of db:*
It is only a regex on the metric path

**Comment by seleznev** [comment]
@rjshrjndrn, we use config like this in our clusters (we combine blacklist (as coarse filter) with whitelist to get only necessary metrics):

```yaml
blacklist:
  # Mostly for RPC, do not scrap them
  # - org:apache:cassandra:db:.*
  - org:apache:cassandra:db:batchlogmanager:.*
  - org:apache:cassandra:db:caches:.*
  - org:apache:cassandra:db:dynamicendpointsnitch:.*
  - org:apache:cassandra:db:indexcolumnfamilies:.*
  - org:apache:cassandra:db:indexsummaries:.*
  - org:apache:cassandra:db:indextables:.*
  - org:apache:cassandra:db:nativeaccess:.*
  - org:apache:cassandra:db:storageproxy:.*
[...]

maxScrapFrequencyInSec:
  15:
    - org:apache:cassandra:db:storageservice:livenodes
    - org:apache:cassandra:db:storageservice:unreachablenodes
[...]
```

May be it will be useful example for you.

p.s. I'm sorry for ignore you question (I don't check notifications too often). :slightly_frowning_face:

**Comment by rjshrjndrn** [comment]
@seleznev Thank you for the detailed example. I've been looking around for a single reg ex to only scrape `storageservice`.
What do you meant by whitelist? if you don't mind can you gimme your config? I'm getting lots of metrics, and now kind of lost.  So it'll be a great help if I can get a real-world config.

**Comment by seleznev** [comment]
@rjshrjndrn,

> What do you meant by whitelist?

`maxScrapFrequencyInSec` is a whitelist actually. It's decribed in [README.md](https://github.com/criteo/cassandra_exporter#how-to-use):

> In the maxScrapFrequencyInSec, you specify the metrics you want to be scraped at which frequency. Basically, starting from the set of all mbeans, the blacklist is applied first to filter this set and then the maxScrapFrequencyInSec is applied as a whitelist to filter the resulting set.

> a single reg ex to only scrape `storageservice`

Did you try something like this:

```yaml
blacklist:
  - ^(?!org:apache:cassandra:db:storageservice).+

maxScrapFrequencyInSec:
  15:
    - .*
```

May be not the best solution but it works for me. :man_shrugging: Or if you want to get only `livenodes`:

```yaml
blacklist:
  - ^(?!org:apache:cassandra:db:storageservice).+

maxScrapFrequencyInSec:
  15:
    - org:apache:cassandra:db:storageservice:livenodes
```

> if you don't mind can you gimme your config?

There it is (as is):

```yaml
blacklist:
  # To profile the duration of jmx call you can start the program with the following options
  # > java -Dorg.slf4j.simpleLogger.defaultLogLevel=trace -jar cassandra_exporter.jar config.yml --oneshot
  #
  # To get intuition of what is done by cassandra when something is called you can look in cassandra
  # https://github.com/apache/cassandra/tree/trunk/src/java/org/apache/cassandra/metrics
  # Please avoid to scrape frequently those calls that are iterating over all sstables

  # Unaccessible metrics (not enough privilege)
  - java:lang:memorypool:.*usagethreshold.*

  # Leaf attributes not interesting for us but that are presents in many path
  - .*:999thpercentile
  - .*:95thpercentile
  - .*:fifteenminuterate
  - .*:fiveminuterate
  - .*:durationunit
  - .*:rateunit
  - .*:stddev
  - .*:meanrate
  - .*:mean
  - .*:min

  # Path present in many metrics but uninterresting
  - .*:viewlockacquiretime:.*
  - .*:viewreadtime:.*
  - .*:cas[a-z]+latency:.*
  - .*:colupdatetimedeltahistogram:.*

  # Mostly for RPC, do not scrap them
  # - org:apache:cassandra:db:.*
  - org:apache:cassandra:db:batchlogmanager:.*
  - org:apache:cassandra:db:caches:.*
  - org:apache:cassandra:db:dynamicendpointsnitch:.*
  - org:apache:cassandra:db:indexcolumnfamilies:.*
  - org:apache:cassandra:db:indexsummaries:.*
  - org:apache:cassandra:db:indextables:.*
  - org:apache:cassandra:db:nativeaccess:.*
  - org:apache:cassandra:db:storageproxy:.*

  # columnfamily is an alias for Table metrics
  # https://github.com/apache/cassandra/blob/8b3a60b9a7dbefeecc06bace617279612ec7092d/src/java/org/apache/cassandra/metrics/TableMetrics.java#L162
  - org:apache:cassandra:metrics:columnfamily:.*

  # Should we export metrics for system keyspaces/tables ?
  - org:apache:cassandra:metrics:[^:]+:system[^:]*:.*

  # Some another uninterresting metrics
  - org:apache:cassandra:metrics:indextable:.*
  - org:apache:cassandra:metrics:indexcolumnfamily:.*

  - .*:waitingonfreememtablespace:.*
  - .*:estimatedpartitionsizehistogram:.*
  - .*:estimatedcolumncounthistogram:.*

  # Don't scrap us
  - com:criteo:nosql:cassandra:exporter:.*

maxScrapFrequencyInSec:
  15:
    - java:lang:garbagecollector:.*
    - java:lang:memory:.*
    - java:lang:threading:.*
    - org:apache:cassandra:db:compactionmanager:compactions
    - org:apache:cassandra:db:compactionmanager:corecompactorthreads
    - org:apache:cassandra:db:compactionmanager:corevalidationthreads
    - org:apache:cassandra:db:compactionmanager:maximumcompactorthreads
    - org:apache:cassandra:db:storageservice:livenodes
    - org:apache:cassandra:db:storageservice:unreachablenodes
    - org:apache:cassandra:metrics:cache:keycache:hits:count
    - org:apache:cassandra:metrics:cache:keycache:requests:count
    - org:apache:cassandra:metrics:client:connectednativeclients:value
    - org:apache:cassandra:metrics:clientrequest:.*:latency:count
    - org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate
    - org:apache:cassandra:metrics:clientrequest:read:timeouts:count
    - org:apache:cassandra:metrics:clientrequest:read:totallatency:count
    - org:apache:cassandra:metrics:clientrequest:read:unavailables:count
    - org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate
    - org:apache:cassandra:metrics:clientrequest:write:timeouts:count
    - org:apache:cassandra:metrics:clientrequest:write:totallatency:count
    - org:apache:cassandra:metrics:clientrequest:write:unavailables:count
    - org:apache:cassandra:metrics:compaction:bytescompacted:count
    - org:apache:cassandra:metrics:compaction:pendingtasks:value
    - org:apache:cassandra:metrics:compaction:totalcompactionscompleted:count
    - org:apache:cassandra:metrics:storage:.*
    - org:apache:cassandra:metrics:table:[^:]+:[^:]+:percentrepaired:value
    - org:apache:cassandra:metrics:table:percentrepaired:value
    - org:apache:cassandra:metrics:threadpools:.*:activetasks:value
    - org:apache:cassandra:metrics:threadpools:.*:pendingtasks:value
    - org:apache:cassandra:metrics:threadpools:.*:totalblockedtasks:count

  # Refresh those metrics only every hour as it is costly for cassandra to retrieve them
  3600:
    - .*:snapshotssize:.*
    - .*:estimated.*
    - .*:totaldiskspaceused:.*
```

But some notes, that must be told:

* It is not cover you case (we scrape `org:apache:cassandra:db:storageservice:livenodes` and __many__ other metrics).
* I'm not a Cassandra expert (or even experienced user), so __never use this config without review__ (examples in this repo much more useful, i.e. https://github.com/criteo/cassandra_exporter/blob/master/config_minimal_dashboard.yml).
